-- MySQL Script generated by MySQL Workbench
-- vie 05 mar 2021 13:36:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema torneo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema torneo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `torneo` DEFAULT CHARACTER SET utf8 ;
USE `torneo` ;

-- -----------------------------------------------------
-- Table `torneo`.`playing_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo`.`playing_position` (
  `position_id` VARCHAR(2) NOT NULL,
  `position_desc` VARCHAR(15) NULL,
  PRIMARY KEY (`position_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneo`.`soccer_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo`.`soccer_country` (
  `country_id` INT NOT NULL,
  `country_abbr` VARCHAR(4) NOT NULL,
  `country_name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneo`.`player_mast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo`.`player_mast` (
  `player_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `jersey_no` INT NOT NULL,
  `player_name` VARCHAR(40) NOT NULL,
  `posi_to_play` VARCHAR(2) NOT NULL,
  `dt_of_bir` DATE NOT NULL,
  `age` INT NOT NULL,
  `playing_club` VARCHAR(40) NULL,
  INDEX `fk_player_mast_playing_position_idx` (`posi_to_play` ASC) VISIBLE,
  PRIMARY KEY (`player_id`),
  INDEX `fk_player_mast_soccer_country1_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `fk_player_mast_playing_position`
    FOREIGN KEY (`posi_to_play`)
    REFERENCES `torneo`.`playing_position` (`position_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_mast_soccer_country1`
    FOREIGN KEY (`team_id`)
    REFERENCES `torneo`.`soccer_country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneo`.`soccer_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo`.`soccer_city` (
  `city_id` INT NOT NULL,
  `city` VARCHAR(25) NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`city_id`),
  INDEX `fk_soccer_city_soccer_country1_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_soccer_city_soccer_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `torneo`.`soccer_country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneo`.`soccer_venue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo`.`soccer_venue` (
  `venue_id` INT NOT NULL,
  `venue_name` VARCHAR(30) NULL,
  `city_id` INT NOT NULL,
  `aud_capacity` INT NOT NULL,
  PRIMARY KEY (`venue_id`),
  CONSTRAINT `fk_soccer_venue_soccer_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `torneo`.`soccer_city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneo`.`soccer_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo`.`soccer_team` (
  `team_id` INT NOT NULL,
  `team_group` CHAR(1) NOT NULL,
  `match_played` INT NOT NULL,
  `won` INT NOT NULL,
  `draw` INT NOT NULL,
  `lost` INT NOT NULL,
  `goal_for` INT NOT NULL,
  `goal_agnst` INT NULL,
  `goal_diff` INT NOT NULL,
  `points` INT NULL,
  `group_position` INT NOT NULL,
  CONSTRAINT `fk_soccer_team_soccer_country1`
    FOREIGN KEY (`team_id`)
    REFERENCES `torneo`.`soccer_country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneo`.`coach_mast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo`.`coach_mast` (
  `coach_id` INT NOT NULL,
  `coach_name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`coach_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneo`.`team_coaches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo`.`team_coaches` (
  `team_id` INT NOT NULL,
  `coach_id` INT NOT NULL,
  PRIMARY KEY (`team_id`, `coach_id`),
  INDEX `fk_team_coaches_soccer_country1_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `fk_team_coaches_coach_mast1`
    FOREIGN KEY (`coach_id`)
    REFERENCES `torneo`.`coach_mast` (`coach_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_coaches_soccer_country1`
    FOREIGN KEY (`team_id`)
    REFERENCES `torneo`.`soccer_country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneo`.`referee_mast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo`.`referee_mast` (
  `referee_id` INT NOT NULL,
  `referee_name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`referee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneo`.`match_mast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo`.`match_mast` (
  `match_no` INT NOT NULL,
  `play_stage` CHAR(1) NOT NULL,
  `play_date` DATE NOT NULL,
  `result` CHAR(5) NOT NULL,
  `decided_by` CHAR(1) NOT NULL,
  `goal_score` CHAR(5) NOT NULL,
  `venue_id` INT NOT NULL,
  `referee_id` INT NOT NULL,
  `audence` INT NOT NULL,
  `plr_of_match` INT NOT NULL,
  `stop1_sec` INT NOT NULL,
  `stop2_sec` INT NOT NULL,
  PRIMARY KEY (`match_no`),
  INDEX `fk_match_mast_referee_mast1_idx` (`referee_id` ASC) VISIBLE,
  INDEX `fk_match_mast_soccer_venue1_idx` (`venue_id` ASC) VISIBLE,
  INDEX `fk_match_mast_player_mast1_idx` (`plr_of_match` ASC) VISIBLE,
  CONSTRAINT `fk_match_mast_referee_mast1`
    FOREIGN KEY (`referee_id`)
    REFERENCES `torneo`.`referee_mast` (`referee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_mast_soccer_venue1`
    FOREIGN KEY (`venue_id`)
    REFERENCES `torneo`.`soccer_venue` (`venue_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_mast_player_mast1`
    FOREIGN KEY (`plr_of_match`)
    REFERENCES `torneo`.`player_mast` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneo`.`played_booked`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo`.`played_booked` (
  `match_no` INT NOT NULL,
  `team_id` INT NOT NULL,
  `player_id` INT NOT NULL,
  `booking_time` VARCHAR(40) NOT NULL,
  `sent_off` CHAR(1) NOT NULL,
  `play_schedule` CHAR(2) NOT NULL,
  `play_half` INT NOT NULL,
  INDEX `fk_played_booked_match_mast1_idx` (`match_no` ASC) VISIBLE,
  INDEX `fk_played_booked_soccer_country1_idx` (`team_id` ASC) VISIBLE,
  INDEX `fk_played_booked_player_mast1_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_played_booked_match_mast1`
    FOREIGN KEY (`match_no`)
    REFERENCES `torneo`.`match_mast` (`match_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_played_booked_soccer_country1`
    FOREIGN KEY (`team_id`)
    REFERENCES `torneo`.`soccer_country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_played_booked_player_mast1`
    FOREIGN KEY (`player_id`)
    REFERENCES `torneo`.`player_mast` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneo`.`player_in_out`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo`.`player_in_out` (
  `match_no` INT NOT NULL,
  `team_id` INT NOT NULL,
  `player_id` INT NOT NULL,
  `in_out` CHAR(1) NOT NULL,
  `time_in_out` INT NOT NULL,
  `play_schedule` CHAR(2) NOT NULL,
  `play_half` INT NULL,
  INDEX `fk_player_in_out_soccer_country1_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `fk_player_in_out_match_mast1`
    FOREIGN KEY (`match_no`)
    REFERENCES `torneo`.`match_mast` (`match_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_in_out_soccer_country1`
    FOREIGN KEY (`team_id`)
    REFERENCES `torneo`.`soccer_country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_in_out_player_mast1`
    FOREIGN KEY (`player_id`)
    REFERENCES `torneo`.`player_mast` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneo`.`goal_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo`.`goal_details` (
  `goal_id` INT NOT NULL,
  `match_no` INT NOT NULL,
  `player_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `goal_time` INT NOT NULL,
  `goal_type` CHAR(1) NOT NULL,
  `play_stage` CHAR(1) NOT NULL,
  `goal_schedule` CHAR(2) NOT NULL,
  `goal_half` INT NOT NULL,
  INDEX `fk_goal_details_match_mast1_idx` (`match_no` ASC) VISIBLE,
  PRIMARY KEY (`goal_id`),
  INDEX `fk_goal_details_player_mast1_idx` (`player_id` ASC) VISIBLE,
  INDEX `fk_goal_details_soccer_country1_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `fk_goal_details_match_mast1`
    FOREIGN KEY (`match_no`)
    REFERENCES `torneo`.`match_mast` (`match_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_goal_details_player_mast1`
    FOREIGN KEY (`player_id`)
    REFERENCES `torneo`.`player_mast` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_goal_details_soccer_country1`
    FOREIGN KEY (`team_id`)
    REFERENCES `torneo`.`soccer_country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneo`.`asst_referee_mast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo`.`asst_referee_mast` (
  `ass_ref_id` INT NOT NULL,
  `ass_ref_name` VARCHAR(40) NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`ass_ref_id`),
  CONSTRAINT `fk_asst_referee_mast_soccer_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `torneo`.`soccer_country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneo`.`match_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo`.`match_details` (
  `match_no` INT NOT NULL,
  `team_id` INT NOT NULL,
  `play_stage` VARCHAR(1) NOT NULL,
  `win_loos` VARCHAR(1) NOT NULL,
  `decided_by` VARCHAR(1) NOT NULL,
  `goal_score` INT NOT NULL,
  `penalty_score` INT NOT NULL,
  `ass_ref_id` INT NOT NULL,
  `player_gk` INT NOT NULL,
  CONSTRAINT `fk_match_details_match_mast1`
    FOREIGN KEY (`match_no`)
    REFERENCES `torneo`.`match_mast` (`match_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_details_asst_referee_mast1`
    FOREIGN KEY (`ass_ref_id`)
    REFERENCES `torneo`.`asst_referee_mast` (`ass_ref_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_details_player_mast1`
    FOREIGN KEY (`player_gk`)
    REFERENCES `torneo`.`player_mast` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_details_soccer_country1`
    FOREIGN KEY (`team_id`)
    REFERENCES `torneo`.`soccer_country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneo`.`penalty_gk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo`.`penalty_gk` (
  `team_id` INT NOT NULL,
  `match_no` INT NOT NULL,
  `player_gk` INT NOT NULL,
  INDEX `fk_penalty_gk_match_mast1_idx` (`match_no` ASC) VISIBLE,
  INDEX `fk_penalty_gk_player_mast1_idx` (`player_gk` ASC) VISIBLE,
  CONSTRAINT `fk_penalty_gk_soccer_country1`
    FOREIGN KEY (`team_id`)
    REFERENCES `torneo`.`soccer_country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_penalty_gk_match_mast1`
    FOREIGN KEY (`match_no`)
    REFERENCES `torneo`.`match_mast` (`match_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_penalty_gk_player_mast1`
    FOREIGN KEY (`player_gk`)
    REFERENCES `torneo`.`player_mast` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneo`.`match_captain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo`.`match_captain` (
  `match_no` INT NOT NULL,
  `team_id` INT NOT NULL,
  `player_captain` INT NOT NULL,
  INDEX `fk_match_captain_soccer_country1_idx` (`team_id` ASC) VISIBLE,
  INDEX `fk_match_captain_match_mast1_idx` (`match_no` ASC) VISIBLE,
  CONSTRAINT `fk_match_captain_soccer_country1`
    FOREIGN KEY (`team_id`)
    REFERENCES `torneo`.`soccer_country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_captain_match_mast1`
    FOREIGN KEY (`match_no`)
    REFERENCES `torneo`.`match_mast` (`match_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_captain_player_mast1`
    FOREIGN KEY (`player_captain`)
    REFERENCES `torneo`.`player_mast` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torneo`.`penalty_shootout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo`.`penalty_shootout` (
  `kick_id` INT NOT NULL,
  `match_no` INT NOT NULL,
  `team_id` INT NOT NULL,
  `player_id` INT NOT NULL,
  `score_goal` VARCHAR(1) NOT NULL,
  `kick_no` INT NOT NULL,
  PRIMARY KEY (`kick_id`),
  INDEX `fk_penalty_shootout_player_mast1_idx` (`player_id` ASC) VISIBLE,
  INDEX `fk_penalty_shootout_match_mast1_idx` (`match_no` ASC) VISIBLE,
  INDEX `fk_penalty_shootout_soccer_country1_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `fk_penalty_shootout_player_mast1`
    FOREIGN KEY (`player_id`)
    REFERENCES `torneo`.`player_mast` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_penalty_shootout_match_mast1`
    FOREIGN KEY (`match_no`)
    REFERENCES `torneo`.`match_mast` (`match_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_penalty_shootout_soccer_country1`
    FOREIGN KEY (`team_id`)
    REFERENCES `torneo`.`soccer_country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
